fix #3076
qiita-spots/qiita pull request #3077
Opened 2021-02-19 19:43 UTC by antgonza

Extra from fixing the above issue, this is also updating to the latests version of DbSchema the qdb/html files.

2021-02-22 21:43 UTC, ElDeveloper requested changes
A few comments. One general question: what are the changes to the DB? Doesn't seem like this issue requires any DB updates, right?

2021-02-22 21:43 UTC, ElDeveloper commented on qiita_db/metadata_template/test/test_util.py
> +                      str(error.exception))
Any reason not to use `assertRaisesRegex`? 

```suggestion
        with self.assertRaisesRegex(RuntimeError, 'Your file has more columns with values than headers'):
            qdb.metadata_template.util.load_template_to_dataframe(
                StringIO('sample_name\tcollection_timestamp\n'
                         '2.Sample1\t2014-05-29 12:24:51\t\n'
                         '2.Sample2\taaa\n'
                         'xxx\tadfa\t\t\n'))
```

2021-02-22 21:43 UTC, ElDeveloper commented on qiita_db/metadata_template/util.py
> +            raise RuntimeError(msg)
Can you add this to the docstring?

2021-02-22 21:48 UTC, antgonza commented
I'll address your suggestions soon. The changes are cause I downloaded the latest version of the DBSchema software and generated the html with the latest version so it's clearer; in other words, nothing really changed just the files to the latest version.

2021-02-22 21:55 UTC, ElDeveloper commented
Makes sense, thanks!

2021-02-23 22:58 UTC, merged

2021-02-23 22:58 UTC, ElDeveloper commented
Thanks @antgonza