2021.07
qiita-spots/qiita pull request #3121
Opened 2021-07-06 17:57 UTC by antgonza

@mestaki, this is how the prep page will look like:
<img width="1283" alt="Screen Shot 2021-07-06 at 8 53 44 AM" src="https://user-images.githubusercontent.com/2014559/124645882-33572b00-de51-11eb-8b1f-b79adda32006.png">

... and this is the new workflow page:
<img width="1802" alt="Screen Shot 2021-07-06 at 8 53 21 AM" src="https://user-images.githubusercontent.com/2014559/124645930-436f0a80-de51-11eb-8c6c-543810daccdd.png">

What do you think?

2021-07-07 22:33 UTC, mestaki commented on qiita_pet/templates/workflows.html
> +        In this page you will find our recommendations on how to processes each data type available in Qiita and the minimum processing requirements to make your data public.
*This is very useful, just some rewording below to hopefully make it more clear for novice users.

----
 In this page you will find our recommendations on how to processes each data type available in Qiita and the minimum processing requirements to make your data public.
        <br/><br/>
        For convenience, there is an "Add Default Workflow" button for each preparation that will add the recommended workflow steps for your raw data which then you can process. It is important to note however that this workflow is based on the default Earth Microbiome Project protocol and so assumes the uploaded data are multiplexed sequences with the reversed barcodes in your mapping file and index  sequence file (see [here](https://earthmicrobiome.org/protocols-and-standards/) for more details). If this protocol does not apply to your data you can still use the Default Workflow, however, you should first manually process your data using the appropriate steps until you have demultiplexed your reads. After demultiplexing the Default Workflow is safe to use with any protocol.
        <br/><br/>
        If you have already manually performed one of the processing steps in the Defaul Workflow pipeline, the "Add Default Workflow" button will not re-select those steps but instead will only select any remaining steps that have not been completed. You can also add additional workflows on top of the recommended Default Workflow at any time.
        <br/><br/>
        Note that this is not a full inclusive list of data types accepted by Qiita but only those that have a <u>defined</u> workflow.
      </div>

2021-07-07 22:41 UTC, mestaki commented on qiita_pet/static/js/networkVue.js
> +             "<br/><a href='https://qiita.ucsd.edu/workflows/' target='_blank'>What's a Default Workflow?</a>" +
I was thinking that if we are not vigilant enough with explaining the EMP assumptions of the Default Workflow we may get a lot of headaches later on when people not-knowingly process their non-EMP protocols. So anything we can to draw their attention to that important aspect I see as time-saving for admin later on.

One suggestion, what about replacing "What's a Default Workflow" to "Important note about Default Workflow"? <- That way they are more likely to read that description with the important note about the demux step. Or maybe adding a :warning: logo beside the button?

2021-07-07 22:46 UTC, mestaki requested changes
Just some rewording and one suggestion about adding a "notice/warning" about EMP dependency of Standard Workflow

2021-07-08 01:50 UTC, antgonza commented
Thank you; now it looks like this:

<img width="1274" alt="Screen Shot 2021-07-07 at 7 47 55 PM" src="https://user-images.githubusercontent.com/2014559/124849637-5e7a7100-df5c-11eb-8542-215cbf7ac3b7.png">

and this:
<img width="1707" alt="Screen Shot 2021-07-07 at 7 48 18 PM" src="https://user-images.githubusercontent.com/2014559/124849639-5fab9e00-df5c-11eb-8f6f-4cbb8e192a6a.png">

Note that I used most of your suggestions but tried to keep the explanation as general as possible by using the target gene example but still mention that there are multiple workflows.

2021-07-08 02:40 UTC, mestaki approved these changes

2021-07-08 02:40 UTC, merged