add method to delete user
qiita-spots/qiita pull request #3173
Opened 2022-01-26 15:11 UTC by antgonza

2022-02-16 18:30 UTC, charles-cowart requested changes

2022-02-16 18:30 UTC, charles-cowart commented on qiita_db/user.py
> +            raise IncorrectEmailError(f'This email does not exists: {email}')
exists -> exist sounds better to my ears.

2022-02-17 04:01 UTC, antgonza commented
@charles-cowart, this is ready for another pass; thank you.

2022-02-17 04:14 UTC, charles-cowart approved these changes
Approved! Thank you so much!

2022-02-17 04:14 UTC, merged