Added prep_id as an optional parameter
qiita-spots/qiita pull request #3262
Opened 2023-03-03 01:15 UTC by charles-cowart

Added prep_id as an optional parameter to
.../study/description/<study_id>?prep_id=<prep_id>.

This will bring up the prep_id workflow page instead of summary information.

2023-03-03 02:14 UTC, charles-cowart commented
@antgonza ready for review. We can remove the --no-check-certificate line in GitHub workflows whenever it's appropriate.

2023-03-05 22:39 UTC, antgonza requested changes
Works great, thank you! A couple of things:
1. if prep-id is not an integer, the code crashes :: expected behavior: do not change frame and display JS error like: "[prep-id] is not a valid preparation for this study".
2. if the prep-id doesn't exist in that study, the window hangs :: expected behavior: similar to point 1.

2023-03-05 22:39 UTC, antgonza commented on .github/workflows/qiita-ci.yml
> +          wget --no-check-certificate https://data.qiime2.org/distro/core/qiime2-2022.11-py38-linux-conda.yml
Please rm `--no-check-certificate`

2023-03-07 05:24 UTC, charles-cowart commented on .github/workflows/qiita-ci.yml
> +          wget --no-check-certificate https://data.qiime2.org/distro/core/qiime2-2022.11-py38-linux-conda.yml
done!

2023-03-07 05:25 UTC, charles-cowart commented
WIP: Unit tests for the new error-checking need to be added, and a change needs to be made to have the error-page only show up in the main frame, but this gets the functionality we need.

2023-03-07 14:48 UTC, antgonza commented
Works as expected and code looks fine. Now, I originally thought a JS (JavaScript) error message should have been enough (see my original review) to let the user know that the prep-id doesn't exist and thought that full HTTPError might be to harsh; however, as this is already done with HTTPError, I think is fine to leave as is and if we get a user feedback we can change to a more simpler JS error + in theory these links should be computer generated.

2023-03-07 14:48 UTC, antgonza approved these changes

2023-03-07 14:48 UTC, merged