fix #3219
qiita-spots/qiita pull request #3278
Opened 2023-04-17 22:13 UTC by charles-cowart

To my knowledge, this appears to fix the outstanding issue. Validation of the two required fields is handled by bootstrap and jinja2. Unselected pulldowns will now display a default tool-tip bubble.

2023-05-22 14:36 UTC, antgonza requested changes
I think this basically fixes/allows for pandas 2.0, right? To test, would you mind changing to dev (vs. master) to see if the tests pass ?

2023-05-22 14:36 UTC, antgonza commented on qiita_db/analysis.py
> +                        si_df = si_df[list(set(categories) &
I think these changes are needed for pandas > 2.0, no?

2023-05-23 17:16 UTC, charles-cowart commented on INSTALL.md
> +conda create -q --yes -n qiita python=3.9 pip libgfortran numpy nginx cython redis
I believe the change was to reflect what was being used in Github Workflows:

https://github.com/charles-cowart/qiita/blob/153fa69e9043c0eb84dfcd014d259485bf38771c/.github/workflows/qiita-ci.yml#L71

2023-05-31 22:01 UTC, antgonza approved these changes

2023-05-31 22:01 UTC, merged